### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by m1337v** [M4cs/Sushi#1]
When I run python3 sushi.py
I get this output:

Traceback (most recent call last):
  File "sushi.py", line 1, in <module>
    from utilities import *
  File "/Users/me/Sushi/Sushi/Sushi/utilities.py", line 49
    api = f'https://api.ipsw.me/v4/device/{identifier}?type=ipsw'
                                                                ^
SyntaxError: invalid syntax

**Comment by M4cs** [comment]
What python3 version?

**Comment by M4cs** [comment]
Fixed with #3
