### ISSUE TITLE
[macOS Mojave] Button widget seems to be broken

### ISSUE THREAD

**Issue by Astrol99** [M4cs/Sushi#2]
When I try to click on it, the window teleports to another location. Is this a problem with the OS or the source code itself?

![feb-02-2019 12-52-23](https://user-images.githubusercontent.com/41875791/52168010-f4ee3c80-26e9-11e9-8c32-eed3754dc27f.gif)

**Comment by M4cs** [comment]
hmm that's weird. It could be due to my method of using an Image as a Button.

**Comment by Astrol99** [comment]
UPDATE: It sent me an error this time

```python
-s: /Users/David/Documents/Sushi/download/tsschecker: Permission denied
Traceback (most recent call last):
  File "/Users/David/Documents/Sushi/PySimpleGUIQt.py", line 3604, in eventFilter
    x_w = self.mouse_offset.x()
AttributeError: 'QT_QMainWindowClass' object has no attribute 'mouse_offset'
[1]    39482 abort      python3 sushi.py
```

edit: Fixed formatting

**Comment by M4cs** [comment]
Permission denied hmmmm. That's really weird. Can you try to download [Athena](https://github.com/M4cs.Athena) or [EGTR](https://github.com/M4cs/EGTR-Futurerestore) and see if the same problem persists?

**Comment by Astrol99** [comment]
Athena was fine. EGTR was a bit buggy though. I tried to enter some invalid args to see what would happen (I didn't plug in my phone :p) and it became a bit broken.

First error was when I inputted nothing and I pressed start:
```python
Traceback (most recent call last):
  File "egtr.py", line 15, in <module>
    screens.mainScreen()
  File "/Users/David/Documents/EGTR-FutureRestore/screens.py", line 164, in mainScreen
    query = futurerestore + blobs_path + base_path + sep_path + latestbase + latestsep + debug + basemani + sepmani + update + nobaseband + wait + ipsw_path
UnboundLocalError: local variable 'blobs_path' referenced before assignment
```

The last error was I inputted invalid args like 'asd' and etc.
At first:
```python
$ python3 egtr.py              

objc[56996]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/FinderKit (0x139a71210) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x13f5afdc8). One of the two will be used. Which one is undefined.
/Users/David/Documents/EGTR-FutureRestore/download/futurerestore -t/Users/David/Documents/EGTR-FutureRestore/asdasd -b /Users/David/Documents/EGTR-FutureRestore/asd -s /Users/David/Documents/EGTR-FutureRestore/asdasd /Users/David/Documents/EGTR-FutureRestore/asd
sh: /Users/David/Documents/EGTR-FutureRestore/download/futurerestore: Permission denied
```
Then a few seconds later, it spammed me this:
```python
Traceback (most recent call last):
  File "/Users/David/Documents/EGTR-FutureRestore/PySimpleGUIQt.py", line 3604, in eventFilter
    x_w = self.mouse_offset.x()
AttributeError: 'QT_QMainWindowClass' object has no attribute 'mouse_offset'
```

**Comment by M4cs** [comment]
okay can you try to remove the PySimpleGUIQt file from the root of the directory. and instead run `pip install PySimpleGUIQt` or do so in a virtualenv

**Comment by Astrol99** [comment]
Same of everything except there aren't anymore of those spams

**Comment by M4cs** [comment]
Did the permission fix it?

**Comment by Astrol99** [comment]
Yeah, but the window rarely teleports now

**Comment by M4cs** [comment]
Hmmm weird. I'll look into another fix.

**Comment by M4cs** [comment]
Didnt mean to close
