### ISSUE TITLE
Error while loading shared libraries: libirecovery.so.2

### ISSUE THREAD

**Issue by Benji-Collins** [M4cs/Sushi#5]
I get this error when I try to save blobs on Ubuntu 18 LTS. I followed the linux install directions in the readme.

![capture](https://user-images.githubusercontent.com/34997963/52256658-80283600-2967-11e9-8708-ac873b55fd6a.PNG)

**Comment by M4cs** [comment]
Closed this because I'm guessing you didnt compile the binaries yourself
