### ISSUE TITLE
Wrong link in Readme

### ISSUE THREAD

**Issue by Benji-Collins** [M4cs/Sushi#6]
The link to EGTR-FutureRestore in the Readme is currently incorrect and leads to a 404. 

What it is now: [https://github.com/M4cs/EGTR-Futurestore](https://github.com/M4cs/EGTR-Futurestore)
What it should be: [https://github.com/M4cs/EGTR-FutureRestore](https://github.com/M4cs/EGTR-FutureRestore)

**Comment by M4cs** [comment]
ty
